import { describe, expect, it } from 'vitest';
import { decodeFeatureCode } from '../src/dictionary/features';
import type { DictLexeme } from '../src/dictionary/types';

const noun: Pick<DictLexeme, 'pos' | 'gender' | 'animacy'> = { pos: 'noun', gender: 'm', animacy: 'anim' };
const impfVerb: Pick<DictLexeme, 'pos' | 'aspect'> = { pos: 'verb', aspect: 'imperfective' };
const pfVerb: Pick<DictLexeme, 'pos' | 'aspect'> = { pos: 'verb', aspect: 'perfective' };

describe('decodeFeatureCode', () => {
  it('x -> uninflected, no features', () => {
    expect(decodeFeatureCode('x')).toEqual({});
  });

  it('nouns: n:sg:gen / n:pl:nom, gender+animacy from the lexeme', () => {
    expect(decodeFeatureCode('n:sg:gen', noun)).toEqual({ number: 'sg', case: 'gen', gender: 'm', animacy: 'anim' });
    expect(decodeFeatureCode('n:pl:nom', noun)).toEqual({ number: 'pl', case: 'nom', gender: 'm', animacy: 'anim' });
  });

  it('adjectives: a:m:sg:nom, a:pl:acc, a:short:f, a:short:pl, a:comp, a:sup', () => {
    expect(decodeFeatureCode('a:m:sg:nom')).toEqual({ gender: 'm', number: 'sg', case: 'nom' });
    expect(decodeFeatureCode('a:pl:acc')).toEqual({ number: 'pl', case: 'acc' });
    expect(decodeFeatureCode('a:short:f')).toEqual({ degree: 'short', number: 'sg', gender: 'f' });
    expect(decodeFeatureCode('a:short:pl')).toEqual({ degree: 'short', number: 'pl' });
    expect(decodeFeatureCode('a:comp')).toEqual({ degree: 'comparative' });
    expect(decodeFeatureCode('a:sup:m:sg:nom')).toEqual({ degree: 'superlative', gender: 'm', number: 'sg', case: 'nom' });
  });

  it('pronouns: p:sg:gen, p:m:sg:nom, p:pl:acc, p:1:sg:nom, p:refl, p:interr:nom', () => {
    expect(decodeFeatureCode('p:sg:gen')).toEqual({ number: 'sg', case: 'gen' });
    expect(decodeFeatureCode('p:m:sg:nom')).toEqual({ gender: 'm', number: 'sg', case: 'nom' });
    expect(decodeFeatureCode('p:pl:acc')).toEqual({ number: 'pl', case: 'acc' });
    expect(decodeFeatureCode('p:1:sg:nom')).toEqual({ pronoun_type: 'personal', person: 1, number: 'sg', case: 'nom' });
    expect(decodeFeatureCode('p:refl')).toEqual({ pronoun_type: 'reflexive' });
    expect(decodeFeatureCode('p:interr:nom')).toEqual({ pronoun_type: 'interrogative', case: 'nom' });
  });

  it('verbs: v:inf, presfut by aspect (present for imperfective, future for perfective), past, imperative', () => {
    expect(decodeFeatureCode('v:inf')).toEqual({ verb_form: 'infinitive' });
    expect(decodeFeatureCode('v:pf:sg1', impfVerb)).toEqual({ verb_form: 'present-future', mood: 'indicative', tense: 'present', number: 'sg', person: 1 });
    expect(decodeFeatureCode('v:pf:pl3', pfVerb)).toEqual({ verb_form: 'present-future', mood: 'indicative', tense: 'future', number: 'pl', person: 3 });
    expect(decodeFeatureCode('v:past:f')).toEqual({ verb_form: 'past', tense: 'past', mood: 'indicative', number: 'sg', gender: 'f' });
    expect(decodeFeatureCode('v:past:pl')).toEqual({ verb_form: 'past', tense: 'past', mood: 'indicative', number: 'pl' });
    expect(decodeFeatureCode('v:imp:sg')).toEqual({ verb_form: 'imperative', mood: 'imperative', number: 'sg' });
  });

  it('verbs: participles and gerunds (generated by package D, decoded here for completeness)', () => {
    expect(decodeFeatureCode('v:pap:m:sg:nom')).toEqual({ verb_form: 'participle-act-pres', voice: 'active', number: 'sg', gender: 'm', case: 'nom' });
    expect(decodeFeatureCode('v:ppp:pl:acc')).toEqual({ verb_form: 'participle-pass-pres', voice: 'passive', number: 'pl', case: 'acc' });
    expect(decodeFeatureCode('v:pps:f')).toEqual({ verb_form: 'participle-short', voice: 'passive', degree: 'short', number: 'sg', gender: 'f' });
    expect(decodeFeatureCode('v:ger:pres')).toEqual({ verb_form: 'gerund-pres', tense: 'present' });
    expect(decodeFeatureCode('v:ger:past')).toEqual({ verb_form: 'gerund-past', tense: 'past' });
  });

  it('numerals: num:nom, num:m:sg:nom', () => {
    expect(decodeFeatureCode('num:nom')).toEqual({ case: 'nom' });
    expect(decodeFeatureCode('num:m:sg:nom')).toEqual({ gender: 'm', number: 'sg', case: 'nom' });
  });

  it('is total: an unrecognised code decodes to {} rather than throwing', () => {
    expect(() => decodeFeatureCode('bogus:code')).not.toThrow();
    expect(decodeFeatureCode('bogus:code')).toEqual({});
  });
});
