/**
 * Decodes the compact FeatureCode strings shipped in FormShard readings (see
 * the grammar documented on `FeatureCode` in types.ts) into MorphFeatures.
 * Pure and total: an unrecognised code decodes to `{}` rather than throwing,
 * since the shard contract may grow (participles/gerunds, generated by
 * package D's rule engine, use the same code grammar) without this file
 * changing in lockstep.
 */
import type { Case, Degree, Gender, MorphFeatures, Number_, Person } from '../database/types';
import type { DecodeFeatureCode } from './types';

const CASES = new Set<Case>(['nom', 'gen', 'dat', 'acc', 'inst', 'prep', 'loc', 'part', 'voc']);
function asCase(s: string | undefined): Case | undefined {
  return s !== undefined && CASES.has(s as Case) ? (s as Case) : undefined;
}
function asNumber(s: string | undefined): Number_ | undefined {
  return s === 'sg' || s === 'pl' ? s : undefined;
}
function asGender(s: string | undefined): Gender | undefined {
  return s === 'm' || s === 'f' || s === 'n' || s === 'common' ? s : undefined;
}

export const decodeFeatureCode: DecodeFeatureCode = (code, lexeme) => {
  const parts = code.split(':');
  const head = parts[0];
  const f: MorphFeatures = {};

  if (head === 'x') return f;

  if (head === 'n') {
    // n:<sg|pl>:<case>
    f.number = asNumber(parts[1]);
    f.case = asCase(parts[2]);
    if (lexeme?.gender) f.gender = lexeme.gender;
    if (lexeme?.animacy) f.animacy = lexeme.animacy;
    return f;
  }

  if (head === 'a') {
    if (parts[1] === 'comp') { f.degree = 'comparative'; return f; }
    if (parts[1] === 'sup') {
      f.degree = 'superlative';
      const g = asGender(parts[2]);
      if (g) f.gender = g;
      f.number = asNumber(parts[3]) ?? 'sg';
      f.case = asCase(parts[4]);
      return f;
    }
    if (parts[1] === 'short') {
      f.degree = 'short' as Degree;
      if (parts[2] === 'pl') f.number = 'pl';
      else { f.number = 'sg'; const g = asGender(parts[2]); if (g) f.gender = g; }
      return f;
    }
    if (parts[1] === 'pl') {
      f.number = 'pl';
      f.case = asCase(parts[2]);
      return f;
    }
    // a:<gender>:sg:<case>
    const g = asGender(parts[1]);
    if (g) f.gender = g;
    f.number = 'sg';
    f.case = asCase(parts[3]);
    return f;
  }

  if (head === 'v') {
    const sub = parts[1];
    if (sub === 'inf') { f.verb_form = 'infinitive'; return f; }
    if (sub === 'pf') {
      f.verb_form = 'present-future';
      f.mood = 'indicative';
      f.tense = lexeme?.aspect === 'perfective' ? 'future' : 'present';
      const m = /^(sg|pl)([123])$/.exec(parts[2] ?? '');
      if (m) { f.number = m[1] as Number_; f.person = Number(m[2]) as Person; }
      return f;
    }
    if (sub === 'past') {
      f.verb_form = 'past'; f.tense = 'past'; f.mood = 'indicative';
      if (parts[2] === 'pl') f.number = 'pl';
      else { f.number = 'sg'; const g = asGender(parts[2]); if (g) f.gender = g; }
      return f;
    }
    if (sub === 'imp') {
      f.verb_form = 'imperative'; f.mood = 'imperative';
      f.number = asNumber(parts[2]);
      return f;
    }
    if (sub === 'pap' || sub === 'paa' || sub === 'ppp' || sub === 'ppa') {
      f.verb_form =
        sub === 'pap' ? 'participle-act-pres' : sub === 'paa' ? 'participle-act-past' : sub === 'ppp' ? 'participle-pass-pres' : 'participle-pass-past';
      f.voice = sub === 'ppp' || sub === 'ppa' ? 'passive' : 'active';
      // v:<pap|paa|ppp|ppa>:pl:<case> | v:<pap|paa|ppp|ppa>:<gender>:sg:<case> (parts[3] is the literal "sg")
      if (parts[2] === 'pl') { f.number = 'pl'; f.case = asCase(parts[3]); }
      else { f.number = 'sg'; const g = asGender(parts[2]); if (g) f.gender = g; f.case = asCase(parts[4]); }
      return f;
    }
    if (sub === 'pps') {
      f.verb_form = 'participle-short'; f.voice = 'passive'; f.degree = 'short';
      if (parts[2] === 'pl') f.number = 'pl';
      else { f.number = 'sg'; const g = asGender(parts[2]); if (g) f.gender = g; }
      return f;
    }
    if (sub === 'ger') {
      f.verb_form = parts[2] === 'past' ? 'gerund-past' : 'gerund-pres';
      f.tense = parts[2] === 'past' ? 'past' : 'present';
      return f;
    }
    return f;
  }

  if (head === 'p') {
    if (parts[1] === 'refl') { f.pronoun_type = 'reflexive'; return f; }
    if (parts[1] === 'interr') { f.pronoun_type = 'interrogative'; f.case = asCase(parts[2]); return f; }
    if (parts[1] === '1' || parts[1] === '2' || parts[1] === '3') {
      f.pronoun_type = 'personal';
      f.person = Number(parts[1]) as Person;
      f.number = asNumber(parts[2]);
      f.case = asCase(parts[3]);
      return f;
    }
    if (parts[1] === 'pl') { f.number = 'pl'; f.case = asCase(parts[2]); return f; }
    const g = asGender(parts[1]);
    if (g) { f.gender = g; f.number = 'sg'; f.case = asCase(parts[3]); return f; }
    f.number = asNumber(parts[1]);
    f.case = asCase(parts[2]);
    return f;
  }

  if (head === 'num') {
    const g = asGender(parts[1]);
    if (g) { f.gender = g; f.number = 'sg'; f.case = asCase(parts[3]); return f; }
    f.case = asCase(parts[1]);
    return f;
  }

  return f;
};
